---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/up --version
      register: up_test_output
    - name: up --version
      debug:
        msg: '{{ up_test_output.stdout }}'
