---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: downloading {{ up_url }} to {{ up_exe }}
  become: true
  become_user: root
  get_url:
    url: '{{ up_url }}'
    dest: '{{ up_exe }}'
    mode: 0755
    checksum: '{{ up_checksum }}'
- name: linking {{ up_link }} to {{ up_exe }}
  become: true
  become_user: root
  file:
    src: '{{ up_exe }}'
    dest: '{{ up_link }}'
    state: link
